# Generated by Django 4.1.3 on 2023-04-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=60, null=True)),
                ('car_model', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Wagon', 'Station wagon'), ('Sport', 'Sports Car'), ('Coupe', 'Coupe'), ('Mini', 'Mini van'), ('Van', 'Van'), ('Pickup', 'Pick-up truck'), ('Truck', 'Truck'), ('Other', 'Other')], default='SUV', max_length=100)),
                ('year', models.DateField(null=True)),
                ('car_make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
        ),
    ]
